services:
  - type: web
    name: hall-booking-frontend
    env: static
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
